services:
    blue:
        image: rinpark/phote:latest
        restart: unless-stopped
        container_name: myphote
        environment:
            - TZ=Asia/Seoul
        ports:
            - "8080:8080"
        networks:
            - phote-network

    green:
        image: rinpark/phote:latest
        restart: unless-stopped
        container_name: myphote
        environment:
            - TZ=Asia/Seoul
        ports:
            - "8081:8080"
        networks:
            - phote-network

networks:
    phote-network:
        external: true
