services:
    blue:
        image: adorableco/phote:latest
        restart: unless-stopped
        container_name: blue
        environment:
            - TZ=Asia/Seoul
        ports:
            - "8082:8080"
        networks:
            - phote-network

    green:
        image: adorableco/phote:latest
        restart: unless-stopped
        container_name: green
        environment:
            - TZ=Asia/Seoul
        ports:
            - "8081:8080"
        networks:
            - phote-network

networks:
    phote-network:
        external: true
